server.port: 8888
hewo.db:
  schema: rock
  jdbcUrl: jdbc:mysql://localhost:3306/hewo-site?serverTimezone=UTC
  driverClassName: com.mysql.cj.jdbc.Driver
  username: root
  password: root

#默认
mybatis.db:
  typeAliases:    #支持包名 或 类名（.class 结尾）
    - "org.hewo"
  mappers:        #支持包名 或 类名（.class 结尾）或 xml（.xml结尾 或 *.xml 结尾）
    - "mapping/*.xml"
  configuration:
    cacheEnabled: false
    mapUnderscoreToCamelCase: true
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
  globalConfig:
    banner: false
    metaObjectHandler: "org.hewo.core.support.dso.MetaObjectHandlerImpl"
    dbConfig:
      logicDeleteField: "deleted"
      logicDeleteValue: "2"